// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zzh.grpc.message.hello;

public interface HelloRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.HelloResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
