// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zzh.grpc.message.hello;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
